### ISSUE TITLE
Add xml attrs file to the aar package

### ISSUE THREAD

**Issue by franciscojunior** [jsibbold/zoomage#35]
Hi! Just tried your library today and it works wonderfully! Thank you very much for releasing it.

But when I tried to use some attributes, Android Studio complained that it couldn't find them. After inspecting the aar file, I noticed that the attrs.xml file is missing inside the res folder.

**Comment by jsibbold** [comment]
Hey thanks for reporting this. Just out of curiosity are you using version 1.0 or the snapshot?

**Comment by franciscojunior** [comment]
You are welcome! 


> Just out of curiosity are you using version 1.0 or the snapshot?

Whooops, sorry for saying before. I'm using 1.0. I didn't try the snapshot.

**Comment by jsibbold** [comment]
Yeah, I actually need to promote the snapshot, currently the documentation is for the snapshot I believe, and not 1.0. Bad on me. Can you give the snapshot a try and see if you have the same issues?

**Comment by franciscojunior** [comment]
Sure! I'll give it a try! Thanks for your fast feedback!

**Comment by franciscojunior** [comment]
Latest snapshot works ok! Sorry for bothering you with this. I'm closing the issue now.

**Comment by jsibbold** [comment]
no bother at all, glad it worked for you, I need to push that version to production
