### ISSUE TITLE
Status Code 409 Conflict

### ISSUE THREAD

**Issue by rkanatza** [jsibbold/zoomage#39]
Hey Jeff, 
I've used zoomage in my Android applications before with no error, but I'm getting an error now. See notes below. Hope you can help.

When loading an Android application with the zoomage dependencies, I get the following gradle error:

> Error:Could not GET 'https://oss.jfrog.org/artifactory/oss-snapshot-local/com/android/support/appcompat-v7/25.3.1/appcompat-v7-25.3.1.pom'. Received status code 409 from server: Conflict
> Enable Gradle 'offline mode' and sync project

When I go to the site in the error message (https://oss.jfrog.org/artifactory/oss-snapshot-local/com/android/support/appcompat-v7/25.3.1/appcompat-v7-25.3.1.pom), I see:
`{
"errors": [
{
"status": 409,
"message": "The repository 'oss-snapshot-local' rejected the resolution of an artifact 'oss-snapshot-local:com/android/support/appcompat-v7/25.3.1/appcompat-v7-25.3.1.pom' due to conflict in the snapshot release handling policy."
}
]
}`

Any idea what's going on?

Thanks

**Comment by jsibbold** [comment]
Hi, I've added version 1.1.0 to production, so you can switch to using version 1.1.0 as a non snapshot from jcenter

**Comment by jsibbold** [comment]
Oh you know what, you might need to add jcenter() to your repositories in gradle.

**Comment by rkanatza** [comment]
Ok great! I'm a bit new when it comes to gradle. Could you show me what the new line in the gradle files would be?

Also, will this break existing applications I have that are pointing to the snapshot?

P.s. Thanks for the quick reply!

**Comment by jsibbold** [comment]
can you show me your dependencies and repositories sections from your gradle file?

**Comment by rkanatza** [comment]
Sure! 

`repositories {
    maven { url 'https://oss.jfrog.org/artifactory/oss-snapshot-local' }
}

dependencies {
    ...
    compile 'com.jsibbold:zoomage:1.1.0-SNAPSHOT'
}`

**Comment by jsibbold** [comment]
can you try this for your repositories section
`
repositories {
  jcenter()
  maven { url 'https://oss.jfrog.org/artifactory/oss-snapshot-local' }
}
`

**Comment by rkanatza** [comment]
Just tried it out and got the same error...

I tried it with the "snapshot" ending in the dependencies and without.

**Comment by jsibbold** [comment]
In my latest update, the version of appcompat we are using was updated to a more recent one. Is your support repository up to date?

**Comment by rkanatza** [comment]
Looks like I've got my support version on 24.0.0. 

I'm getting some errors bumping up to the 25.3.1 it requires. Let me do some research on those and get back to you tomorrow. Thanks for your replies today!

**Comment by rkanatza** [comment]
Got it to work by updating the support version from 24.0.0 to 25.3.1.

Thanks for your help!
