### ISSUE TITLE
Add support to clickListener

### ISSUE THREAD

**Issue by franciscojunior** [jsibbold/zoomage#40]
I'd like to handle clicks on the imageview, but when I call setOnClickListener, the listener isn't called.

I think onTouchEvent needs to be patched to detect when a click was done and call the performClick method accordingly. 

Thanks for all the hard work!

**Comment by franciscojunior** [comment]
imageview above is a ZoomageView object, obviously. Just wanted to clarify that. :)

**Comment by jsibbold** [comment]
This is a tough one just because we wouldn't want accidental clicks to interfere with someone making small taps to adjust positioning, etc. I would say if this was added, if clicking is enabled any zoom or translation interaction would have to be disabled at the same time, and vice versa.

**Comment by jsibbold** [comment]
the latest snapshot should take into account whether the view is clickable
