### ISSUE TITLE
After setting a bigger Bitmap you can't zoom out

### ISSUE THREAD

**Issue by hurzl** [jsibbold/zoomage#41]
If the Bitmap set by `setImageBitmap(Bitmap)` is bigger than the bitmap that was loaded before, it is impossible zoom out enough to fit into the View

**Comment by jsibbold** [comment]
Just out of curiosity, did you try setting the scale type to CENTER_FIT after setting the new image?

**Comment by hurzl** [comment]
I didn't set any scale type, but just setting it once in the layout xml helped. What is the default?

**Comment by hurzl** [comment]
Now I have the problem when the new image is smaller. I don't want to reset because I would like to keep the zoom when switching images, but if the image is smaller than the View, it should be fit ...
I have AutoResetMode set to UNDER, but it doesn't work on a new image.

**Comment by jsibbold** [comment]
The main problem here is that the matrix being used is tailored to the first image, and is based on the starting scale of that first image. When you add a new image, you'll likely need to copy that matrix, load the new image with a CENTER_FIT scale type, and then change the scale type to MATRIX and load that matrix in with setImageMatrix.

**Comment by jsibbold** [comment]
latest snapshot should fix this
