### ISSUE TITLE
Issue resetting zoomed image before changing image

### ISSUE THREAD

**Issue by dgcooke** [jsibbold/zoomage#42]
When image is zoomed right in then change images the new image is at the same zoom level as the last image even if I do a ZoomageView.reset() first.

Is there a way to reset the zoom to 1?

Damien

**Comment by jsibbold** [comment]
Run ImageView.setScaleType(FIT_CENTER) on the new image (or whatever ScaleType you set by default on the original image, if you want something besides FIT_CENTER)
