### ISSUE TITLE
Issue with ViewPager

### ISSUE THREAD

**Issue by tabassumLatif** [jsibbold/zoomage#45]
When i zoom image and swipe left or right then view pager swipe not image.

**Comment by jsibbold** [comment]
Is this only when the image is zoomed, or is this happening any time you swipe?

**Comment by MilapPancholi** [comment]
Yes this was happing when my image was zoom and at that time i drag it view pager has been changed

**Comment by jsibbold** [comment]
try latest snapshot for this

**Comment by manoj-basavaraja** [comment]
With the latest implementation 'SNAPSHOT', facing the same issue, unable to navigate to next view, when the image is zoomed.

**Comment by jsibbold** [comment]
@manoj-basavaraja That is intentional. If the image is zoomed, the assumption is that it's being interacted with. Zooming back out should allow navigation.
