### ISSUE TITLE
Zoom factor

### ISSUE THREAD

**Issue by Ceddi23** [jsibbold/zoomage#46]
How can i get zoom factor? 
ex. zoomed (2x), zoomed (1.63x)

Edit:
and also how can i get x and y coordinates of displayed part of ZoomageView after i zoom in?

**Comment by Ceddi23** [comment]
I am overriding ontouch event after i zoom in to draw something on image. the problem is the x and y coordinates of canvas is not match in x and y coords of displayed part of zoomageview after i zoom in

**Comment by Ceddi23** [comment]
Am overriding ontouch after i zoom in to draw on image using canvas. The problem is after i zoom in, the x and y coordinates of zoomageview is still for the whole canvas. I want to match MotionEvent coordinates of zoomageview to the displayed part of canvas on zoomageview.

**Comment by jsibbold** [comment]
zoom factor has been added in the latest snapshot
