### ISSUE TITLE
Having multiple images in viewpager is not zooming

### ISSUE THREAD

**Issue by Thejas88** [jsibbold/zoomage#48]
In Viewpager which is horizontal swiping, the first image is zoomable but the rest of the images are not able to zoom.

**Comment by jsibbold** [comment]
I'll need to look more into this, but I'm wondering if ViewPager is consuming the touch events.

**Comment by MonoBiit** [comment]
So, what if it's true?
I have a ZoomageView in my recyclerview (Horizontal) and I cannot zoom anyway.

**Comment by jsibbold** [comment]
Please try latest snapshot

**Comment by shirtleton** [comment]
@jsibbold The update you did for 1.3.0 seems to have improved functionality when `ZoomageView` is used in conjunction with a view pager. Do you have an ETA on when 1.3.0 will be released?

**Comment by jsibbold** [comment]
@shirtleton I'll try to get that release out by end of week

**Comment by jsibbold** [comment]
@shirtleton sorry it took me a bit longer, but 1.3.0 should be good and up on jcenter. Let me know if any issues arise getting it.
