### ISSUE TITLE
Add support for double-tap to zoom

### ISSUE THREAD

**Issue by aberaud** [jsibbold/zoomage#49]
Great library, thanks !
Would be nice if it allowed to zoom-in/zoom-out of the image by double-tapping on it.

Double-tapping would toggle-animate between the full-screen state and the original image size, which seems to be the standard behavior of most image-viewing widgets.

**Comment by aberaud** [comment]
Just saw #44 and #38. I believe double-tap to zoom is an important feature that most users expect. Please keep this open until it's implemented :-)

**Comment by jsibbold** [comment]
Double tapping would animate a larger zoom factor on the location that was tapped?

**Comment by aberaud** [comment]
yes

**Comment by jsibbold** [comment]
this is now available in the 1.2.0 snapshot

**Comment by Noltibus** [comment]
Any word on when this will be available in the stable version?

**Comment by rvats011990** [comment]
Hi Very good library. Please add double tap zoom option soon...

**Comment by MobiDevelop** [comment]
Any chance you have time do a stable release with this? Would like this feature but am not able to use snapshot versions in my project.

**Comment by jsibbold** [comment]
Okay, I pushed up a release version today for 1.2.0. I still need to update this project for newer versions of the Android Gradle Plugin, but for now this version 1.2.0 should be good. Let me know if you run into any issues.
