### ISSUE TITLE
Zoom is very difficult when you are inside a ScrollView

### ISSUE THREAD

**Issue by shiriuki** [jsibbold/zoomage#53]
When the ZoomageView is inside an ScrollView and your content doesn´t fit in the screen and the scroll view is enabled, using the ZoomageView functionality is a mess because it conflicts with the scroll bar.

**Comment by HodaTabasi** [comment]
not zooming inside scrollView  
just can scroll ZoomageView up and down 
but can not zoom it in and out

**Comment by jsibbold** [comment]
The latest snapshot has a fix for this
