### ISSUE TITLE
Could not find library

### ISSUE THREAD

**Issue by blackhawk389** [jsibbold/zoomage#57]
When I'm trying to download using gradle snapshot library I'm getting following errors on android studio 3.0.0

Error:Could not find com.jsibbold:zoomage:1.2.0-SNAPSHOT.
Searched in the following locations:
    file:/E:/Android/sdk/extras/m2repository/com/jsibbold/zoomage/1.2.0-SNAPSHOT/maven-metadata.xml
    file:/E:/Android/sdk/extras/m2repository/com/jsibbold/zoomage/1.2.0-SNAPSHOT/zoomage-1.2.0-SNAPSHOT.pom
    file:/E:/Android/sdk/extras/m2repository/com/jsibbold/zoomage/1.2.0-SNAPSHOT/zoomage-1.2.0-SNAPSHOT.jar
    file:/E:/Android/sdk/extras/google/m2repository/com/jsibbold/zoomage/1.2.0-SNAPSHOT/maven-metadata.xml
    file:/E:/Android/sdk/extras/google/m2repository/com/jsibbold/zoomage/1.2.0-SNAPSHOT/zoomage-1.2.0-SNAPSHOT.pom
    file:/E:/Android/sdk/extras/google/m2repository/com/jsibbold/zoomage/1.2.0-SNAPSHOT/zoomage-1.2.0-SNAPSHOT.jar
    file:/E:/Android/sdk/extras/android/m2repository/com/jsibbold/zoomage/1.2.0-SNAPSHOT/maven-metadata.xml
    file:/E:/Android/sdk/extras/android/m2repository/com/jsibbold/zoomage/1.2.0-SNAPSHOT/zoomage-1.2.0-SNAPSHOT.pom
    file:/E:/Android/sdk/extras/android/m2repository/com/jsibbold/zoomage/1.2.0-SNAPSHOT/zoomage-1.2.0-SNAPSHOT.jar
    file:/F:/android-studio-ide-171.4182969-windows/android-studio/gradle/m2repository/com/jsibbold/zoomage/1.2.0-SNAPSHOT/maven-metadata.xml
    file:/F:/android-studio-ide-171.4182969-windows/android-studio/gradle/m2repository/com/jsibbold/zoomage/1.2.0-SNAPSHOT/zoomage-1.2.0-SNAPSHOT.pom
    file:/F:/android-studio-ide-171.4182969-windows/android-studio/gradle/m2repository/com/jsibbold/zoomage/1.2.0-SNAPSHOT/zoomage-1.2.0-SNAPSHOT.jar
    http://mobile.useinsider.com/com/jsibbold/zoomage/1.2.0-SNAPSHOT/maven-metadata.xml
    http://mobile.useinsider.com/com/jsibbold/zoomage/1.2.0-SNAPSHOT/zoomage-1.2.0-SNAPSHOT.pom
    http://mobile.useinsider.com/com/jsibbold/zoomage/1.2.0-SNAPSHOT/zoomage-1.2.0-SNAPSHOT.jar
    https://jcenter.bintray.com/com/jsibbold/zoomage/1.2.0-SNAPSHOT/maven-metadata.xml
    https://jcenter.bintray.com/com/jsibbold/zoomage/1.2.0-SNAPSHOT/zoomage-1.2.0-SNAPSHOT.pom
    https://jcenter.bintray.com/com/jsibbold/zoomage/1.2.0-SNAPSHOT/zoomage-1.2.0-SNAPSHOT.jar
    https://repo1.maven.org/maven2/com/jsibbold/zoomage/1.2.0-SNAPSHOT/maven-metadata.xml
    https://repo1.maven.org/maven2/com/jsibbold/zoomage/1.2.0-SNAPSHOT/zoomage-1.2.0-SNAPSHOT.pom
    https://repo1.maven.org/maven2/com/jsibbold/zoomage/1.2.0-SNAPSHOT/zoomage-1.2.0-SNAPSHOT.jar
    https://raw.github.com/Matthias247/jawampa/mvn-repo/com/jsibbold/zoomage/1.2.0-SNAPSHOT/maven-metadata.xml
    https://raw.github.com/Matthias247/jawampa/mvn-repo/com/jsibbold/zoomage/1.2.0-SNAPSHOT/zoomage-1.2.0-SNAPSHOT.pom
    https://raw.github.com/Matthias247/jawampa/mvn-repo/com/jsibbold/zoomage/1.2.0-SNAPSHOT/zoomage-1.2.0-SNAPSHOT.jar
    https://jitpack.io/com/jsibbold/zoomage/1.2.0-SNAPSHOT/maven-metadata.xml
    https://jitpack.io/com/jsibbold/zoomage/1.2.0-SNAPSHOT/zoomage-1.2.0-SNAPSHOT.pom
    https://jitpack.io/com/jsibbold/zoomage/1.2.0-SNAPSHOT/zoomage-1.2.0-SNAPSHOT.jar
    https://dl.google.com/dl/android/maven2/com/jsibbold/zoomage/1.2.0-SNAPSHOT/maven-metadata.xml
    https://dl.google.com/dl/android/maven2/com/jsibbold/zoomage/1.2.0-SNAPSHOT/zoomage-1.2.0-SNAPSHOT.pom
    https://dl.google.com/dl/android/maven2/com/jsibbold/zoomage/1.2.0-SNAPSHOT/zoomage-1.2.0-SNAPSHOT.jar
    https://maven.fabric.io/public/com/jsibbold/zoomage/1.2.0-SNAPSHOT/maven-metadata.xml
    https://maven.fabric.io/public/com/jsibbold/zoomage/1.2.0-SNAPSHOT/zoomage-1.2.0-SNAPSHOT.pom
    https://maven.fabric.io/public/com/jsibbold/zoomage/1.2.0-SNAPSHOT/zoomage-1.2.0-SNAPSHOT.jar
    https://s3.amazonaws.com/repo.commonsware.com/com/jsibbold/zoomage/1.2.0-SNAPSHOT/maven-metadata.xml
    https://s3.amazonaws.com/repo.commonsware.com/com/jsibbold/zoomage/1.2.0-SNAPSHOT/zoomage-1.2.0-SNAPSHOT.pom
    https://s3.amazonaws.com/repo.commonsware.com/com/jsibbold/zoomage/1.2.0-SNAPSHOT/zoomage-1.2.0-SNAPSHOT.jar
Required by:
    project :app

**Comment by jsibbold** [comment]
you need to add this repository https://oss.jfrog.org/artifactory/oss-snapshot-local

**Comment by blackhawk389** [comment]
@jsibbold added still not working

**Comment by blackhawk389** [comment]
repositories {
        jcenter()
        mavenCentral()
        maven {
            url 'https://raw.github.com/Matthias247/jawampa/mvn-repo/'
        }
        maven { url 'https://oss.jfrog.org/artifactory/oss-snapshot-local' }
        google()
    }

or 

repositories {
        jcenter()
        mavenCentral()
        maven {
            url 'https://raw.github.com/Matthias247/jawampa/mvn-repo/',
                    url 'https://oss.jfrog.org/artifactory/oss-snapshot-local'
        }
        
        google()
    }

not working
