### ISSUE TITLE
Image is cropped when restrictBounds is true and scaleType is FIT_XY

### ISSUE THREAD

**Issue by aiavci** [jsibbold/zoomage#62]
### Description
When you set `restrictBounds = true` and the `scaleType` property for the view to `FIT_XY`, the image gets cropped.

Note: This bug is inconsistent and may require you to zoom in, out and move the image slightly.

**Comment by jsibbold** [comment]
This is likely related to issues with how fitxy differs from other scale types. I'll look into a possible solution but for now fitXY will exhibit strange behavior.
