### ISSUE TITLE
Can't swipe ViewPager

### ISSUE THREAD

**Issue by adeldolgov** [jsibbold/zoomage#77]
After update to 1.3.0 i can't swipe to left right inside viewpager. How can i fix it?
 I can't change images

**Comment by jsibbold** [comment]
If you're swiping on the actual image, it's going to prioritize translating and/or zooming the image over swiping pages.

**Comment by adeldolgov** [comment]
Then how can i swipe horizontally, if i have full match parent zoomageView?

**Comment by adeldolgov** [comment]
Also is there any zoom listener avalaible?

**Comment by jsibbold** [comment]
Can you check to see if it works by setting translatable to false?

**Comment by adeldolgov** [comment]
It works, but then i can't swipe on image

**Comment by adeldolgov** [comment]
If you have zoom listener, then i can just disable ViewPager paging, and reenable when picture zoomout

**Comment by jsibbold** [comment]
currently there isn't but you could override onTouchEvent and check the current zoom factor there and make your calls, then return super.onTouchEvent

**Comment by jsibbold** [comment]
A zoom listener has been requested and I am planning to add it sometime soon though. In the mean time I would try the suggestion above.

**Comment by adeldolgov** [comment]
How can i check inside onTouchEvent if image was zoomed?

**Comment by jsibbold** [comment]
getCurrentScaleFactor

**Comment by adeldolgov** [comment]
Thanks! I fixed the issue.

**Comment by adeldolgov** [comment]
Let me explain how i fixed it : 
Inside PagerAdapter :

**Comment by jsibbold** [comment]
Glad you got it working, it's a difficult thing figuring out how to prioritize overlapped touchable views. I may consider adding a bit of logic specifically for views that have not been zoomed at all, for translation. The only potential problem I see there is if someone has centerCropped an image and it's bigger than the visible area, they wouldn't be able to translate and may want to.

**Comment by adeldolgov** [comment]
Okay. Thank you for the library!

**Comment by adeldolgov** [comment]
@jsibbold this solution allows to move picture left/right sides when picture zoomed inside ViewPager item. Without this when you using horizontal scrolling it will change picture (or ViewPager item), not move zoom.

**Comment by parthanjaria** [comment]
Awesome solution. 
Just one change now while using viewpager2(new component) is :

`zoomageView.setOnTouchListener(new View.OnTouchListener() {
                @Override
                public boolean onTouch(View view, MotionEvent motionEvent) {
                    if(zoomageView.getCurrentScaleFactor()>1f || zoomageView.getCurrentScaleFactor()<1f) {
                        listener.onImageZoomed(true);
                        zoomageView.setTranslatable(true);
                    }
                    else {
                        listener.onImageZoomed(false);
                        zoomageView.setTranslatable(false);
                    }

                    return zoomageView.onTouchEvent(motionEvent);
                }
            });`

**Comment by jsibbold** [comment]
I'll work on a solution for this problem in the next snapshot. I would want to add some options for it so devs can decide whether they want this behavior or not.
