### ISSUE TITLE
View gets locked when changing layout params

### ISSUE THREAD

**Issue by ArnyminerZ** [jsibbold/zoomage#92]
Hi, I'm trying to make that a ZoomageView gets "fullscreen" when you double touch it, instead of simply zooming.

To make that, I've created a custom GestureDetector, this code:
```kotlin
class GestureListener(private val mainActivity: MainActivity) :
    GestureDetector.SimpleOnGestureListener() {
    companion object {
        private const val TAG = "GestureListener"
    }

    private var zoomed = false

    override fun onDoubleTap(e: MotionEvent?): Boolean {
        super.onDoubleTap(e)

        val displayMetrics = DisplayMetrics()
        mainActivity.windowManager.defaultDisplay.getMetrics(displayMetrics)
        val screenHeight = displayMetrics.heightPixels
        val imageViewParams = mainActivity.imageView.layoutParams
        imageViewParams.height = screenHeight * 1 / 2
        mainActivity.imageView.layoutParams = if (zoomed) imageViewParams
            else ConstraintLayout.LayoutParams(
                ConstraintLayout.LayoutParams.MATCH_PARENT,
                ConstraintLayout.LayoutParams.MATCH_PARENT
            )
        zoomed = !zoomed

        mainActivity.imageView.invalidate()

        return true
    }
}
```
What I'm trying to do there is to set the imageView's height to half the screen height, and when you double click, it fills the parent view.
The thing is that some times (mostly always) when the view changes size it gets blocked, I can't zoom in, out or move the image, and I have to close and reopen the app, to see the same behavior again.
I'm not getting any errors, so I am a bit confused.
I've tried doing it the ugly way, creating two imageView, and when double clicking one hiding that, and showing the other, see this code:
```kotlin
class GestureListener(private val mainActivity: MainActivity) :
    GestureDetector.SimpleOnGestureListener() {
    companion object {
        private const val TAG = "GestureListener"
    }

    private var zoomed = false

    override fun onDoubleTap(e: MotionEvent?): Boolean {
        super.onDoubleTap(e)

        visibility(mainActivity.sector_imageView, !zoomed)
        visibility(mainActivity.imageView_full, zoomed)

        zoomed = !zoomed

        mainActivity.imageView.invalidate()
        mainActivity.imageView_full.invalidate()

        return true
    }
}
```
Where `visibility` is:
```kotlin
fun visibility(view: View, visible: Boolean, setGone : Boolean = true, debug: Boolean = false){
    view.visibility = if(visible) View.VISIBLE else if(setGone) View.GONE else View.INVISIBLE
}
```
But I am having the same issue. Locked view, no errors... What am I doing wrong? Thanks in advance.

**Comment by jsibbold** [comment]
Are you using the latest version?

**Comment by ArnyminerZ** [comment]
@jsibbold yes, I even installed `1.3.1-SNAPSHOT` to check if that was the issue, but still the same.

**Comment by jsibbold** [comment]
When you change the actual size of the view, are you resetting the scaleType?

**Comment by ArnyminerZ** [comment]
Nope. Should I? How do I do that?

**Comment by jsibbold** [comment]
Give it a try, try calling setScaleType(ScaleType.FIT_CENTER)

**Comment by ArnyminerZ** [comment]
Ok, that worked perfectly. Tank you very much!
Best regards.
