### ISSUE TITLE
No method to retain zoom level

### ISSUE THREAD

**Issue by usmanrana07** [jsibbold/zoomage#93]
Hi! I need to retain the zoom level when drawable changes in the view. Currently when I show thumbnail in the ImageView and zoom the image then when Glide loads the actual image. The zoom state is reset, I need to retain it in that case.
Currently I've handled it like this:

```
    @Override
    public void setScaleType(@Nullable ScaleType scaleType) {
        // To retain zoom level on Drawable change i.e. when actual image loads after thumbnail
        if (!isZoomed()) {
            super.setScaleType(scaleType);
        }
    }
```

**Comment by jsibbold** [comment]
Does this solution work correctly for you?

**Comment by usmanrana07** [comment]
Yes, So far.

**Comment by jsibbold** [comment]
Then I would continue to use that, ZoomageView is not designed to retain state across a drawable change.
