### ISSUE TITLE
Image bounds are not restricted when zooming.

### ISSUE THREAD

**Issue by ArnyminerZ** [jsibbold/zoomage#94]
I have a `ZoomageView` with `zoomage_restrictBounds` set to true, and when dragging with a finger, this is perfect, but when you drag with two fingers, when zooming, for example, it allows you to exit the boundaries.
Is it a bug, a feature or I do need to set up something else?
Thank you very much.

**Comment by jsibbold** [comment]
That is intentional, as it could make zooming feel less natural if the bounds were suddenly restricted.
