### ISSUE TITLE
Issue when changing orientation in a ViewPager

### ISSUE THREAD

**Issue by agonshehu** [jsibbold/zoomage#95]
When you change orientation, the images change dimension and position (they become smaller and at the top corner). No idea why.

**Comment by jsibbold** [comment]
I'm unable to reproduce this issue. Mine resets to its default position and size based on ScaleType. What ScaleType are you using? Do you have any zoomage settings that are not the default settings enabled?

**Comment by serdarakin** [comment]
Problem occurs when rotating the picture after zooming

**Comment by KamilKeenan** [comment]
I'm also having the same problem, any info about some update? Any workaround? Maybe resetting view somehow? Please help!

**Comment by jsibbold** [comment]
Try calling reset(), if that doesn't work try setting the scale type to what you started with.

**Comment by KamilKeenan** [comment]
> Try calling reset(), if that doesn't work try setting the scale type to what you started with.

Oh, great. You mean, after rotating device right? (I need to check when user rotates it?)
reset() view or activity?

**Comment by jsibbold** [comment]
Yeah after orientation change

**Comment by KamilKeenan** [comment]
it works! I am just setting scale type again :) thx so much!
